#!/bin/bash

# Purge everything for testings sake
docker rm -f $(docker ps -a -q)
docker volume rm $(docker volume ls -q)

# Build the containers and bring them online
docker-compose build
docker-compose up -d

sleep 5
# Create the database
docker exec PG psql postgres -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'delivery';" \
  | grep -q 1 | docker exec PG psql postgres -U postgres -c "CREATE DATABASE delivery WITH ENCODING 'UTF8';"

# Create tables
docker exec TP python -c 'from trackpack.database import init_db; init_db()'

# Run down then up to bring container to forground once all commands are done running.
docker-compose stop
docker-compose up

# Execute testing suite
docker exec -t TP pytest
