version: '3'

services:
  web:
    container_name: TP
    build: .
    command: python api.py
    #restart: always
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./trackpack:/src
    env_file:
      - .env
    ports:
      - "5000:5000"

  db:
    container_name: PG
    image: postgres
    #restart: always
    environment:
      - POSTGRES_PASSWORD
    expose:
      - "5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
