version: '3'

services:
  web:
    container_name: TP
    build: .
    command: gunicorn -b 0.0.0.0:5000 wsgi:app --worker-class=eventlet --workers=5 --threads=4 --timeout 120 --log-level=debug --log-file - --max-requests=5120 --max-requests-jitter=1000 --worker-tmp-dir=/dev/shm
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./trackpack:/src
    env_file:
      - .env
    ports:
      - "5000:5000"

  db:
    container_name: PG
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
    expose:
      - "5432"
    networks:
      - backend
    volumes:
      - ./migrate.sql:/tmp/migrate.sql

networks:
  backend:
    driver: bridge
